baseURL = 'https://ic4907.github.io/'
languageCode = 'en-us'
title = '蒋大培的博客'


theme = "cactus"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4


[params]
  copyright = "Dapei Jiang"
  description = "你好，我是蒋大培。欢迎来到我的个人博客！我是一名热爱软件开发的工程师，这个博客是我与你分享技术见解、源码阅读心得以及对于技术的深入理解的平台。在这里，我会分享我的编程旅程，记录我在探索代码世界时的点滴体会。无论是最新的技术趋势、代码优化的技巧还是对于软件开发过程中的挑战和解决方案，我都会尽可能地将我的心得体会与你分享。如果你对于某个特定主题感兴趣，也欢迎在评论区留言，我们一起探讨、交流，共同进步。除了技术分享，我还会不定期地发布一些生活感悟、读书笔记等内容，希望能够在技术探索的同时，与你分享更多关于生活的美好与思考。"
  mainSection = "posts"
  tocInline = false
  showProjectsList = true
  projectsUrl = "https://github.com/ic4907"


[[params.social]]
  name = "github"
  link = "https://github.com/ic4907"

[[params.social]]
  name = "email"
  link = "shalir@outlook.com"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/ic4907/"

[params.comments]
    enabled = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 2